### ISSUE TITLE
Having problem with ZPool.map_async() as it runs function sequentially.

### ISSUE THREAD

**Issue by bakhsanzh** [uber/fiber#11]
Hello, I'm trying to use fiber in my Distributed Deep RL project and wanted to understand the basics of the fiber (and python multiprocessing). I am not sure why, but the code below does **not** run in parallel. Can anyone explain to me what am I doing wrong?
I'm using Anaconda Python 3.7.7 on Ubuntu Linux 18.04 LTS.
```
import fiber
import time


def do_something(sleep_time):
    time.sleep(sleep_time)
    return 'func id: {}, sleep time: {}'.format(sleep_time, sleep_time)


def main():
    s = time.perf_counter()
    pool = fiber.Pool(processes=4)
    times_list = [3, 1, 2, 4]

    handle = pool.map_async(do_something, times_list)
    results = handle.get()
    for i in results:
        print(i)

    dt = time.perf_counter() - s
    print(dt)


if __name__ == '__main__':
    main()

```
![image](https://user-images.githubusercontent.com/21025649/80385018-88f48700-88e0-11ea-843c-997b1dbc6933.png)

**Comment by calio** [comment]
Hi @bakhsanzh, thanks for trying out Fiber! The problem you see is related to how Fiber schedules workload and pool chunk size.

1. Fibe uses round-robin scheduling to schedule all jobs among all workers that are currently **active**.
2. There is some slight delay between when `fiber.Pool` is called and when workers are actually started.
3. fiber.Pool also has a default [chunksize](https://uber.github.io/fiber/pool/#fiber.pool.ZPool.map_async) which is 32. This is to improve efficiency when running large amount of workload.

So to make the example work, I changed a few places:

1. Added a `time.sleep(0.5)` after pool creation. You might need to adjust the value on your machine
2. Added a third argument which specifies chunksize 1  to `pool.map_async`

Complete code:

```python
import fiber
import time
import os


def do_something(sleep_time):
    pid = os.getpid()
    time.sleep(sleep_time)
    return 'func id: {}, sleep time: {}, pid: {}'.format(sleep_time, sleep_time, pid)


def main():
    s = time.perf_counter()
    pool = fiber.Pool(processes=4)
    times_list = [3, 1, 2, 4]
    time.sleep(0.5)

    handle = pool.map_async(do_something, times_list, 1)
    results = handle.get()
    for i in results:
        print(i)

    dt = time.perf_counter() - s
    print(dt)


if __name__ == '__main__':
    main()
```
I also printed out the PID that each task is running so that it's easier to figure out if all the tasks are scheduled in the same worker process.

<img width="334" alt="Screen Shot 2020-04-27 at 10 29 39 AM" src="https://user-images.githubusercontent.com/233995/80401983-12b93b80-8872-11ea-9101-47e0c7d6a1fa.png">

**Comment by bakhsanzh** [comment]
Hi @calio, thanks for the clear explanation! I'll close the issue.

**Comment by bakhsanzh** [comment]
Hi @calio, thanks for the clear explanation. Indeed everything works as expected. However, I observed an interesting behavior related to this `time.sleep(0.5)` before running `map_async`: 
1. If I comment out the `time.sleep(0.5)` it takes approximately 5.2 seconds to finish the run.
![image](https://user-images.githubusercontent.com/21025649/80463022-86db0880-8972-11ea-9333-0061d61be97d.png)
2. If I leave the `time.sleep(0.5)` it takes 4.51 seconds. Which considering 0.5 sleep means it, effectively took 0.01 seconds to start processes (in contrast to 1.2 seconds in (1)).

I guess that having a time buffer of 0.5 seconds (in this case) helps fiber to start workers. However, if I don't provide the time buffer, it will mess something up and require **even more time** to perform the tasks. 

Considering the aforementioned, I have the following questions:
1. Is providing a time buffer (sleep) for workers to start, is a general rule of thumb for using Fiber?
2. Can we observe the same pattern of behavior with other Fiber classes? Specifically, I'm concerned about AsyncManager since I want to run multiple gym environments in parallel.

**Comment by calio** [comment]
Hi @bakhsanzh 

> Is providing a time buffer (sleep) for workers to start, is a general rule of thumb for using Fiber?
Not really. The idea behind that is that you can get thing started even if not all the workers are up. This is useful when running jobs on a busy cluster when you can't get all the resources you want. If you would like to wait for all the worker to be up, you can call `pool.wait_until_workers_up()`. 

> Can we observe the same pattern of behavior with other Fiber classes? Specifically, I'm concerned about AsyncManager since I want to run multiple gym environments in parallel.

AsyncManager doesn't have that issue because AsyncManager only works when all the manager has been started. So it won't have the same issue that Pool has.
